
---
- name: reboot
  command: 'reboot'
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for
      host='{{ IPADDR }}'
      port=22
      delay=10
  become: false
