# tasks/configure_vlan.yml

---

- name: Load 8021q module
  modprobe:
    name: 8021q

- name: Add 8021q module to /etc/modules
  shell: 'sudo su -c "echo 8021q >> /etc/modules"'
  become: yes

- name: Create ifcfg file for VLAN interface
  copy:
    content: |
      DEVICE=enp0s3.30
      BOOTPROTO=none
      ONBOOT=yes
      IPADDR=10.33.84.5
      NETMASK=255.255.255.128
      NETWORK=10.33.84.0
      VLAN=yes
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3.30

- name: Create rule file for VLAN interface
  copy:
    content: 'from 10.33.84.0/25 tab 1 priority 500'
    dest: /etc/sysconfig/network-scripts/rule-enp0s3.30

- name: Create route file for VLAN interface
  copy:
    content: 'default via 10.33.84.1 dev enp0s3.30 table 1'
    dest: /etc/sysconfig/network-scripts/route-enp0s3.30

- name: Create sysctl override file
  copy:
    content: |
      net.ipv4.ip_forward=1
      net.ipv4.conf.all.arp_filter=0
      net.ipv4.conf.all.rp_filter=2
    dest: /etc/sysctl.d/90-override.conf

- name: apply sysctl settings
  command: sysctl -p /etc/sysctl.d/90-override.conf

- name: reboot
  command: reboot
  async: 1
  poll: 0
  ignore_errors: yes
