
---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no