# tasks/iptables.yml

---
# - name: Install iptables
#   yum:
#     name:
#       - iptables
#       - iptables-services
#     state: latest


# - name: Set default rules
#   shell: '{{ item }}'
#   with_items:
#     - iptables -F
#     - iptables -A INPUT -i lo -j ACCEPT
#     - iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#     - iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
#     - iptables -P INPUT DROP
#     - iptables -P FORWARD DROP
#     - iptables -P OUTPUT DROP    
#     - iptables -A INPUT -p icmp --icmp-type 8 -j ACCEPT
#     - iptables -A OUTPUT -p icmp --icmp-type 8 -j ACCEPT
#     - iptables -A INPUT -p tcp --dport 80 -j ACCEPT
#     - iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
#     - iptables -A INPUT -p udp -m udp --dport 5060 -j ACCEPT
#     - iptables -A INPUT -p udp -m udp --dport 69 -j ACCEPT
#     - iptables -A INPUT -p udp -m udp --dport 10000:20000 -j ACCEPT
#     - service iptables save
  

# - name: Restart iptables service
#   command: systemctl restart iptables
  # ignore_errors: yes